---
kind: pipeline
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: voltagex
    password:
      from_secret: docker_auth
    repo: voltagex/fedora-mingw64-rtlsdr
    dockerfile: fedora-mingw64-rtlsdr/Dockerfile